# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: On C++
author: Arech
# email: your-email@example.com
# tagline: A short description
description: >- # this means to ignore newlines until "baseurl:"
  Some thoughts on C++ and Software Engineering.

baseurl: "" # the subpath of your site, e.g. /blog
domain: "arech.github.io"
url: "https://arech.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#google_site_verification

show_downloads: false
# TODO: add GA , also read https://github.com/pages-themes/midnight#customizing-google-analytics-code
# google_analytics: 

#twitter_username: jekyllrb
linkedin_username: alrech
github_username:  Arech

# Build settings
theme: minima
show_excerpts: true

#disqus:
#    shortname: my_disqus_shortname
#TODO https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# note that all remote themes tried don't support important layout page property, see notes.txt
# more on it https://github.com/pages-themes/midnight
#remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
#  - jekyll-remote-theme # for midnight theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - my_notes.txt  
    - .vs/
    - .git/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
    posts:
        permalink: /:year-:month-:day-:title
